### PR TITLE
Support for Firefox

### PR DESCRIPTION
**Pull request by lachlandcp**
This pull request adds the necessary metadata for the extension to work in Firefox.

I have tested this with Firefox 54.0.1, which is the latest stable version, and it works as expected.

### CODE REVIEW

**Comment by stu-blair** [comment]
Thank you very much for your contribution! I did not realize it was so simple to add Firefox support. I tested on my Firefox and confirmed that it works! Also, good call on adding `node_modules` to the `.git-ignore`.

However, it seems that Chrome does not like the new entry in the `manifest.json`. It throws an error "Unrecognized manifest key 'applications'." 
See this thread https://stackoverflow.com/questions/37127330/unrecognized-manifest-key-applications-warning-for-google-chrome

I'm not sure what is the cleanest solution. Currently, whenever I have an update for the extension, I simply have to zip up the build folder and upload that. This would add several extra steps where I'd have to manually alter the `manifest.json` between uploading the updated extension to Chrome and Firefox. Have any solutions on how to make this process easier?

**Comment by lachlandcp** [comment]
@stu-blair This commit does the job pretty well. I've modified Gulp to create two versions in the `build/` directory, one with the Chrome manifest and one with the Firefox manifest. Then, can easily zip up or select the right browser directory.

This does also add the dev dependency `gulp-json-transform`.

**Comment by lachlandcp** [comment]
@stu-blair I've made a couple of changes, irrelevant to the Firefox support.

The first is that the black box's padding was making it wider than the element it was hiding, so I added a CSS rule to ensure the box would not be wider.

The second is that I saw #GameOfThones (no R) trending on Twitter earlier, which escaped the extension. I have added 'gameofthone' to the list of spoiler words.

**Review by lachlandcp — COMMENTED** [review]
Somehow I had 'content-box' instead of 'border-box', despite testing it successfully with the latter.

**Comment by stu-blair** [comment]
All looks great, thanks so much for your contributions @imnofox  !

**Comment by lachlandcp** [comment]
@stu-blair Awesome! Will you be putting this on the Firefox addons marketplace?

**Comment by stu-blair** [comment]
@imnofox yes I definitely intend to soon.

**Comment by lachlandcp** [comment]
@stu-blair Do you mind if I handle the Firefox submission? I'm quite eager to get this properly installed! 😁

**Comment by lachlandcp** [comment]
@stu-blair is the extension up on the Firefox addons marketplace yet? I can't find it.

**Comment by stu-blair** [comment]
@imnofox , give it a try! https://addons.mozilla.org/en-US/firefox/addon/gameofspoils/

**Comment by lachlandcp** [comment]
@stu-blair 😬 the link's broken?

**Pull request merged**
